# Generated by Django 2.2.17 on 2021-07-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.BigIntegerField(help_text='account id', verbose_name='account_id')),
                ('is_member_withdrawn', models.BooleanField(default=False, help_text='동의한 멤버 탈퇴 여부', verbose_name='is_member_withdrawn')),
            ],
        ),
    ]
